### ISSUE TITLE
Replace the Markdown parser

### ISSUE THREAD

**Issue by evanplaice** [vanillawc/wc-markdown#1]
The current parser (ie Showdown) does a great job but its huge (ie 150K+) for what it provides and doesn't support ESM syntax out-of-the-box.

**Requirements**

1. small size (1-2KB preferred)
2. written in ESM-first style
3. compatibility with Prism.js

**Potential Options**

[Snarkdown][]

- meets 1 & 2
- code blocks missing `language-` prefix may be fixable with a PrismJS plugin
- no `<table>` tag support
- looks like it hasn't been updated in over a year

[Micro-Down][]

- meets 1 & 2
- code blocks have not supported

[Snarkdown]: https://github.com/developit/snarkdown
[Micro-Down]: https://github.com/commit-intl/micro-down

**Comment by willsteinmetz** [comment]
Would this also solve the problem of it stripping out whitespace from inside of code blocks within the markdown? It's entirely possible that is a different problem but I'm running into it now and if so, I can open another issue.

Right now what is happening is that I have a code block in the markdown for HTML like:

```html
<header>
  <nav>
    <a href="#"
      class="hello">
      Link 1
    </a>
    <a href="#"
      class="hello">
      Link 2
    </a>
    <a href="#"
      class="hello">
      Link 3
    </a>
  </nav>
</header>
```

But it comes out like:

```html
<header>
<nav>
<a href="#"
class="hello">
Link 1
</a>
<a href="#"
class="hello">
Link 2
</a>
<a href="#"
class="hello">
Link 3
</a>
</nav>
</header>
```

It's not a huge deal but it doesn't look super pretty :/

Otherwise, this component works great and is easy to use! Thanks for creating it!

**Comment by evanplaice** [comment]
Damn. I was trying to compensate for indentation when used on inline Markdown but my correction caused this.

Anyway, I fixed it. NPM should have a new version 1.0.3.

**Comment by willsteinmetz** [comment]
That's awesome! Thank you so much for fixing it so fast! :D

**Comment by evanplaice** [comment]
I'm glad you like it. I have a lot of fun building these. If you don't mind me asking, where is it being used?

**Comment by willsteinmetz** [comment]
We're using it for documentation at work on an internal library. Making double use of the readme markdown file.

**Comment by evanplaice** [comment]
Nice. Thank you for sharing.

**Comment by willsteinmetz** [comment]
@evanplaice was able to double-check it this morning and that's definitely working now for us! Thanks again for the quick fix!

**Comment by evanplaice** [comment]
The parser used in this package has been switched from Showdown to Marked.

Changes:

- the 'tables' attribute is no longer necessary to parse MD tables, Marked does this by default
- the dist bundle size reduced from 193K to 64K
- using the non-dist version will likely see much larger improvements
