### ISSUE TITLE
Not parsing tables

### ISSUE THREAD

**Issue by wintercounter** [vanillawc/wc-markdown#6]
Tables are getting rendered as a single paragraph.

Showdown needs `tables: true` to enable the support for it. I'll make a PR.

**Comment by wintercounter** [comment]
Can you please release the new version including this?

**Comment by evanplaice** [comment]
Done. Sorry about the delay.

I sent you an invite to the org. That should grant push access to this repo, if not let me know.

If you need to publish a new version do `npm publish [minor|patch]` and the CI/CD will automatically publish a new version. Just don't introduce API breaking changes without prior discussion.
